project:
  type: book
  output-dir: docs

book:
  title: "CCESR Intern Hub"
  author: "CCESR Fellows"
  chapters:
    - index.qmd
    - part: "Data Management"
      chapters: 
        - dm_intro.qmd
        - dm_record.qmd
        - dm_organize.qmd
        - dm_document.qmd
        - dm_process.qmd
    - part: "Data Analysis"
      chapters: 
        - da_glance.qmd
        - da_data.qmd
        - da_describe.qmd
        - da_infer.qmd
    - part: "R on your Computer"
      chapters:
        - rc_r.qmd
        - rc_rstudio.qmd
        - rc_git.qmd
    - part: "R Programming"
      chapters: 
        - r_basics.qmd
        - r_next.qmd
        - r_import.qmd
        - r_wrangle.qmd
        - r_summarize.qmd
        - r_analyze.qmd
        - r_visualize.qmd
    - part: "Appendices"
      chapters: 
        - appendix_a.qmd

comments:
  hypothesis: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

