---
title: "Documentation and Storage"
toc: true
---

“Your primary collaborator is yourself 6 months from now & your past self doesn’t answer email!”\
\
- Rachel Ainsworth

Taking notes as you conduct research and backing things up are both generally good practice. Here are some things to think about regarding both:

## Document

**What** **to document:**

-   File-specific info or metadata

    -   file naming patterns

    -   variable/attribute definitions

-   Technical steps

    -   data collection

    -   processing (what did you include or exclude?)

    -   analysis steps

-   External data sources

-   Software used with version numbers

-   Meeting notes

-   Organization schemes

**Where to document:**

-   Lab Notebook

    -   Can be physical or digital

    -   Many scientists use pen for this sort of thing

-   Field notebook

    -   Generally easier to be physical if taking notes in the field, can be digital if taking notes at end of day

-   ReadMe file

    -   Good for computer work - data processing and analysis

**When to document:**

-   Set aside \~15 minutes after your work session

-   Develop a regular routine during the research process

    -   Easier to do than remembering everything at the end

-   Can also note things opportunistically as you go

    -   jot potentially relevant observations down in a notebook

    -   comment out code

## Store

The methods of backing up your data may vary somewhat based on medium, but what remains important universally is to maintain multiple formats of backups, and it is helpful to have one backup in an alternative physical location.

**Paper Data Sheets**

-   take a photo or scan each newly filled data sheet after each day of data collection

-   Back up entered data files in cloud storage or some other location

**Electronic Data**

-   Download a dated copy of all electronically entered files after each day of data collection

    -   You can write an R script to do this for you with Google Sheets

You may also run into some issues when storing backups. You may run out of storage space, especially on personal cloud storage accounts. However, usually university or organization based accounts have large storage limits. In addition, physical data drives (either hard drives or solid-state drives) can fail, so it's good to have cloud-based storage and/or alternate physical drives (another computer or external drive) as fail-safes. Of course, cloud storage providers can change terms in the near future, so be prepared for adapting your plans.
